[package]
name = "multithreading_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
crossbeam-channel = "0.5.8"
log = "0.4.19"
stderrlog = "0.5.4"
threadpool = "1.8.1"
